### ISSUE TITLE
Each time starting PC resets settings?

### ISSUE THREAD

**Issue by ParanoIIa91** [Gnarus-G/maccel#15]
Each time i start PC, i need to redo settings and type "sudo maccel bindall" in order for accel to work again.

**Comment by Gnarus-G** [comment]
I'd say when you get this issue, uninstall: `curl -fsSL https://www.maccel.org/uninstall.sh | sudo sh`
And reisntall `curl -fsSL https://www.maccel.org/install.sh | sudo sh`
