### ISSUE TITLE
"Maccel bindall" command doesnt detect/bind my alpakka device?

### ISSUE THREAD

**Issue by ParanoIIa91** [Gnarus-G/maccel#16]
![Screenshot_20240502_212923](https://github.com/Gnarus-G/maccel/assets/74189594/3a323ed1-06eb-455e-8c59-1c8099a427a1)

**Comment by Gnarus-G** [comment]
Let me know if after trying out #23 it works or not.
If not, then give me the output of `sudo dmesg | grep maccel`
