### ISSUE TITLE
After update it does not work at all.

### ISSUE THREAD

**Issue by ParanoIIa91** [Gnarus-G/maccel#17]
![Screenshot_20240504_101118](https://github.com/Gnarus-G/maccel/assets/74189594/5007b828-7ad4-4362-b7bf-c3932ffda990)
![Screenshot_20240504_100916](https://github.com/Gnarus-G/maccel/assets/74189594/82e80d66-9d98-48a0-a27f-62695114adb7)
After running commands sudo maccel bindall and sudo maccel tui, this is what i am getting.

**Comment by Gnarus-G** [comment]
I'd say when you get this issue, uninstall: `curl -fsSL https://www.maccel.org/uninstall.sh | sudo sh`
And reisntall `curl -fsSL https://www.maccel.org/install.sh | sudo sh`
