### ISSUE TITLE
Not working for Razor Deathadder Elite V2

### ISSUE THREAD

**Issue by GENERALCHEEZITZ** [Gnarus-G/maccel#22]
I know it's listed as one of the devices that works, but for some odd reason not for me. I tested this with another wired usb mouse I had lying around and it works. I don't get any kind of error when the device binds, it just says it binds and the mouse just stops working completely, no movement and no button input. I saw this as an issue with leetmouse, but the issue was closed with no conclusion https://github.com/systemofapwne/leetmouse/issues/41.

**Comment by Gnarus-G** [comment]
Well to be fair, what is listed is not the Elite one.
I am working on a fix for these kind of issues. In fact you can help me if you would, try out the new implementation of the driver in this PR #23
It's a work in progress, but I need to know if I'm getting somewhere.

**Comment by Gnarus-G** [comment]
Closing this since it's pretty much a duplicate issue from #9
