### ISSUE TITLE
Can you explain what this driver is used for?

### ISSUE THREAD

**Issue by jackywu** [Gnarus-G/maccel#27]
Can you explain what this driver is used for?
I guess it is to allow ordinary mice on Linux to have the same acceleration performance as Mac Mouse on macOS?

thanks for your following response.

**Comment by Gnarus-G** [comment]
Gaming, mostly: variable sensitivity for different situations. You can read the first couple of paragraphs on https://maccel.org and/or checkout this video, https://www.youtube.com/watch?v=SBXv0xi-wyQ for more context.
